name: Build Check

on:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install-build-essential
      run: sudo apt-get update && sudo apt-get install build-essential libbsd-dev -y

    - name: checkout
      uses: actions/checkout@v3

    - name: build
      run: make
