name: Norm Check

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on:
    steps:

    - name: norm
      run: /Library/Frameworks/Python.framework/Versions/3.11/bin/norminette
