name: Norm Check

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: norm
      run: echo "Hello\n"
